/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FcdsRouteImport } from './routes/fcds'
import { Route as NaqyaRouteImport } from './routes/naqya'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as FcdsCourseSlugRouteImport } from './routes/fcds.course.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FcdsRoute = FcdsRouteImport.update({
  id: '/fcds',
  path: '/fcds',
  getParentRoute: () => rootRouteImport,
} as any)
const NaqyaRoute = NaqyaRouteImport.update({
  id: '/naqya',
  path: '/naqya',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FcdsCourseSlugRoute = FcdsCourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => FcdsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/fcds': typeof FcdsRouteWithChildren
  '/naqya': typeof NaqyaRoute
  '/watch/$id': typeof WatchIdRoute
  '/fcds/course/$slug': typeof FcdsCourseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/fcds': typeof FcdsRouteWithChildren
  '/naqya': typeof NaqyaRoute
  '/watch/$id': typeof WatchIdRoute
  '/fcds/course/$slug': typeof FcdsCourseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/fcds': typeof FcdsRouteWithChildren
  '/naqya': typeof NaqyaRoute
  '/watch/$id': typeof WatchIdRoute
  '/fcds/course/$slug': typeof FcdsCourseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/fcds'
    | '/naqya'
    | '/watch/$id'
    | '/fcds/course/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/explore'
    | '/fcds'
    | '/naqya'
    | '/watch/$id'
    | '/fcds/course/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/fcds'
    | '/naqya'
    | '/watch/$id'
    | '/fcds/course/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExploreRoute: typeof ExploreRoute
  FcdsRoute: typeof FcdsRouteWithChildren
  NaqyaRoute: typeof NaqyaRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fcds': {
      id: '/fcds'
      path: '/fcds'
      fullPath: '/fcds'
      preLoaderRoute: typeof FcdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naqya': {
      id: '/naqya'
      path: '/naqya'
      fullPath: '/naqya'
      preLoaderRoute: typeof NaqyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fcds/course/$slug': {
      id: '/fcds/course/$slug'
      path: '/course/$slug'
      fullPath: '/fcds/course/$slug'
      preLoaderRoute: typeof FcdsCourseSlugRouteImport
      parentRoute: typeof FcdsRoute
    }
  }
}

interface FcdsRouteChildren {
  FcdsCourseSlugRoute: typeof FcdsCourseSlugRoute
}

const FcdsRouteChildren: FcdsRouteChildren = {
  FcdsCourseSlugRoute: FcdsCourseSlugRoute,
}

const FcdsRouteWithChildren = FcdsRoute._addFileChildren(FcdsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExploreRoute: ExploreRoute,
  FcdsRoute: FcdsRouteWithChildren,
  NaqyaRoute: NaqyaRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
